Controllers/LeaderboardController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Qwiz.Data;
using Qwiz.Models;
using Remotion.Linq.Parsing.Structure.IntermediateModel;

namespace Qwiz.Controllers
{
    [Route("leaderboard")]
    public class LeaderboardController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly UserManager<ApplicationUser> _um;
        
        public LeaderboardController(ApplicationDbContext db, UserManager<ApplicationUser> um)
        {
            _db = db;
            _um = um;
        }
        
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        
        [HttpGet("{id}")]
        public async Task<IActionResult> Quiz(int id)
        {
            var quiz = await _db.Quizzes.Where(q => q.Id == id).FirstOrDefaultAsync();

            if (quiz == null)
                return NotFound();
            
            return View(quiz);
        }
    }
}

Controllers/QuizController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Qwiz.Data;
using Qwiz.Models;

namespace Qwiz.Controllers
{
    [Route("quiz")]
    public class QuizController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly UserManager<ApplicationUser> _um;
        private readonly Random _ran = new Random();
        
        public QuizController(ApplicationDbContext db, UserManager<ApplicationUser> um)
        {
            _db = db;
            _um = um;
        }
        
        public async Task<IActionResult> Index()
        {
            if (QuizUtil.OfTheDayTimer < DateTime.Now)
            {
                if (await _db.Quizzes.CountAsync() >= 6)
                {
                    QuizUtil.OfTheDayList = await UpdateOfTheDay();
                }
            }
            
            return View(QuizUtil.OfTheDayList);
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> Play(int? id)
        {
            if (id == null) return NotFound();
            
            var quiz = await _db.Quizzes
                .Include(c => c.Questions)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (quiz == null) return NotFound();
            
            // Remove the correct answers, client should not have this information
            quiz.Questions.ForEach(q =>
            {
                q.CorrectAnswer = "";
            });
            
            return View(quiz);
        }
        
        [HttpGet("create")]
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        [HttpGet("edit/{id}")]
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) return NotFound();
            
            Quiz quiz = await _db.Quizzes
                .Include(q => q.Questions)
                .FirstOrDefaultAsync(q => q.Id == id);
            if (quiz == null) return NotFound();

            if (quiz.OwnerUsername == _um.GetUserName(User))
                return View("../Quiz/Create", quiz);
            
            return NotFound();
        }

        [HttpGet("summary/{id}")]
        [Authorize]
        public async Task<IActionResult> Summary(int? id)
        {
            if (id == null) return NotFound();

            var user = await _db.Users
                .Include(u => u.QuizzesTaken)
                .ThenInclude(q => q.QuestionsTaken)
                .Include(u => u.QuizzesTaken)
                .ThenInclude(q => q.Quiz)
                .ThenInclude(q => q.Questions)
                .SingleOrDefaultAsync(u => u.Id == _um.GetUserId(User));
            
            if (user != null) {
                var quizTaken = user.QuizzesTaken.Find(q => q.Quiz.Id == id);
                if (quizTaken == null) return NotFound();

                return View(quizTaken);
            }
            
            return BadRequest();
        }
        
        private async Task<List<Quiz>> UpdateOfTheDay()
        {
            var newQuizList = new List<Quiz>();
            var quizList = QuizUtil.OfTheDayList.ToList();
            QuizUtil.OfTheDayTimer = DateTime.Now.AddHours(12);

            for (var i = 0; i < 3; i++)
            {
                var quiz = await _db.Quizzes.Where(q => quizList.All(q2 => q2.Id != q.Id)).FirstOrDefaultAsync();
                if (quiz == null) break;
                
                quizList.Add(quiz);
                newQuizList.Add(quiz);
            }
            
            return newQuizList;
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Qwiz</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-custom.css" />
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/material-icons.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <script src="https://unpkg.com/axios/dist/axios.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-custom.min.css"/>
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/material-icons.min.css" />
        <link rel="stylesheet" href="~/css/site.min.css" />
        <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.min.js"></script>
    </environment>
    
    <script src="https://unpkg.com/vuejs-paginate@latest"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Qwiz</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Quiz" asp-action="Index">Play</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Quiz" asp-action="Create">Create</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Leaderboard" asp-action="Index">Leaderboard</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Group" asp-action="Index">Groups</a>
                        </li>
                     </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
        <div>
            <div class="modal" id="modalGlobal"tabindex="-1" role="dialog">
                <div class="modal-dialog" role="document">
                    <div class="modal-content bg-danger">
                        <div class="modal-header">
                            <h5 class="modal-title">Error</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <p id="globalModalMsg"></p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Qwiz
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
        <script src="~/js/site.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    <script>
        global.isAuthenticated = @Json.Serialize(User.Identity.IsAuthenticated);
        global.currentUserName = @Json.Serialize(User.Identity.Name);
        
        if (global.isAuthenticated) axios.put('/api/user/wakeUp');
    </script>

@RenderSection("Scripts", required: false)
</body>
</html>